- name: Upgrade Ubuntu to the next release
  hosts: localhost
  tasks:

    - name: Ensure the system is fully updated before upgrade
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
